[package]
name = "baby-kyber-rs"
version = "0.1.0"
edition = "2024"
description = "BabyKyber is a down-scaled version of the system Kyber."

[dependencies]
rand = "0.8.5"
serde = { version = "1.0.216", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.133"
